/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(function(){a.config.container_autoresize=!0;a.config.month_day_min_height=90;var q=a._pre_render_events;a._pre_render_events=function(f,d){if(!a.config.container_autoresize)return q.apply(this,arguments);var h=this.xy.bar_height,l=this._colsS.heights,b=this._colsS.heights=[0,0,0,0,0,0,0],c=this._els.dhx_cal_data[0],f=this._table_view?this._pre_render_events_table(f,d):this._pre_render_events_line(f,d);if(this._table_view)if(d)this._colsS.heights=l;else{var g=c.firstChild;
if(g.rows){for(var e=0;e<g.rows.length;e++){b[e]++;if(b[e]*h>this._colsS.height-22){for(var i=g.rows[e].cells,j=0;j<i.length;j++)i[j].childNodes[1].style.height=b[e]*h+"px";b[e]=(b[e-1]||0)+i[0].offsetHeight}b[e]=(b[e-1]||0)+g.rows[e].cells[0].offsetHeight}b.unshift(0)}else if(!f.length&&this._els.dhx_multi_day[0].style.visibility=="visible"&&(b[0]=-1),f.length||b[0]==-1){var m=g.parentNode.childNodes,n=(b[0]+1)*h+1+"px";c.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+
parseInt(n,10)+"px";c.style.height=this._obj.offsetHeight-parseInt(c.style.top,10)-(this.xy.margin_top||0)+"px";var k=this._els.dhx_multi_day[0];k.style.height=n;k.style.visibility=b[0]==-1?"hidden":"visible";k=this._els.dhx_multi_day[1];k.style.height=n;k.style.visibility=b[0]==-1?"hidden":"visible";k.className=b[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small";this._dy_shift=(b[0]+1)*h;b[0]=0}}return f};var o=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],p=function(f){for(var d=
0,h=0;h<o.length;h++){var l=o[h],b=a._els[l]?a._els[l][0]:null,c=0;switch(l){case "dhx_cal_navline":case "dhx_cal_header":c=parseInt(b.style.height,10);break;case "dhx_multi_day":c=b?b.offsetHeight:0;c==1&&(c=0);break;case "dhx_cal_data":var c=Math.max(b.offsetHeight-1,b.scrollHeight),g=a.getState().mode;if(g=="month"){if(a.config.month_day_min_height&&!f)var e=b.getElementsByTagName("tr").length,c=e*a.config.month_day_min_height;if(f)b.style.height=c+"px"}if(a.matrix&&a.matrix[g])if(f)c+=2,b.style.height=
c+"px";else for(var c=2,i=a.matrix[g],j=i.y_unit,m=0;m<j.length;m++)c+=!j[m].children?i.dy:i.folder_dy||i.dy;if(g=="day"||g=="week")c+=2}d+=c}a._obj.style.height=d+"px";f||a.updateView()},d=function(){var d=a.getState().mode;p();(a.matrix&&a.matrix[d]||d=="month")&&window.setTimeout(function(){p(!0)},1)};a.attachEvent("onViewChange",d);a.attachEvent("onXLE",d);a.attachEvent("onEventChanged",d);a.attachEvent("onEventCreated",d);a.attachEvent("onEventAdded",d);a.attachEvent("onEventDeleted",d);a.attachEvent("onAfterSchedulerResize",
d);a.attachEvent("onClearAll",d)})()});
